version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      MONGO_URI: mongodb://mongo:27017/todos
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
